export const products = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/1/1.jpg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
      "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 2,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/2/1.jpg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
      "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: ["https://i.dummyjson.com/data/products/3/1.jpg"],

    publishDate: "24 Dec 2023",
  },
  {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/4/1.jpg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
      "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 5,
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/5/1.jpg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 6,
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "Apple",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: [
      "https://i.dummyjson.com/data/products/6/1.png",
      "https://i.dummyjson.com/data/products/6/2.jpg",
      "https://i.dummyjson.com/data/products/6/3.png",
      "https://i.dummyjson.com/data/products/6/4.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "Samsung",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/7/1.jpg",
      "https://i.dummyjson.com/data/products/7/2.jpg",
      "https://i.dummyjson.com/data/products/7/3.jpg",
      "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/8/1.jpg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
      "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/9/1.jpg",
      "https://i.dummyjson.com/data/products/9/2.png",
      "https://i.dummyjson.com/data/products/9/3.png",
      "https://i.dummyjson.com/data/products/9/4.jpg",
      "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    images: [
      "https://i.dummyjson.com/data/products/10/1.jpg",
      "https://i.dummyjson.com/data/products/10/2.jpg",
      "https://i.dummyjson.com/data/products/10/3.jpg",
      "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 11,
    title: "perfume Oil",
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    price: 13,
    discountPercentage: 8.4,
    rating: 4.26,
    stock: 65,
    brand: "Impression of Acqua Di Gio",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/11/1.jpg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
      "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 12,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 15.66,
    rating: 4,
    stock: 52,
    brand: "Royal_Mirage",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/12/1.jpg",
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/4.jpg",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 13,
    title: "Fog Scent Xpressio Perfume",
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    price: 13,
    discountPercentage: 8.14,
    rating: 4.59,
    stock: 61,
    brand: "Fog Scent Xpressio",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/13/1.jpg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
      "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 14,
    title: "Non-Alcoholic Concentrated Perfume Oil",
    description:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    price: 120,
    discountPercentage: 15.6,
    rating: 4.21,
    stock: 114,
    brand: "Al Munakh",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/14/1.jpg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
      "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 15,
    title: "Eau De Perfume Spray",
    description:
      "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    price: 30,
    discountPercentage: 10.99,
    rating: 4.7,
    stock: 105,
    brand: "Lord - Al-Rehab",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/15/1.jpg",
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 16,
    title: "Hyaluronic Acid Serum",
    description:
      "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
    price: 19,
    discountPercentage: 13.31,
    rating: 4.83,
    stock: 110,
    brand: "L'Oreal Paris",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/16/1.png",
      "https://i.dummyjson.com/data/products/16/2.webp",
      "https://i.dummyjson.com/data/products/16/3.jpg",
      "https://i.dummyjson.com/data/products/16/4.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
    publishDate: "24 Dec 2023",
  },
  {
    id: 17,
    title: "Tree Oil 30ml",
    description:
      "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
    price: 12,
    discountPercentage: 4.09,
    rating: 4.52,
    stock: 78,
    brand: "Hemani Tea",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/17/1.jpg",
      "https://i.dummyjson.com/data/products/17/2.jpg",
      "https://i.dummyjson.com/data/products/17/3.jpg",
      "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    ],
  },
  {
    id: 18,
    title: "Oil Free Moisturizer 100ml",
    description:
      "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    price: 40,
    discountPercentage: 13.1,
    rating: 4.56,
    stock: 88,
    brand: "Dermive",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/18/1.jpg",
      "https://i.dummyjson.com/data/products/18/2.jpg",
      "https://i.dummyjson.com/data/products/18/3.jpg",
      "https://i.dummyjson.com/data/products/18/4.jpg",
      "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    ],
  },
  {
    id: 19,
    title: "Skin Beauty Serum.",
    description:
      "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
    price: 46,
    discountPercentage: 10.68,
    rating: 4.42,
    stock: 54,
    brand: "ROREC White Rice",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/19/1.jpg",
      "https://i.dummyjson.com/data/products/19/2.jpg",
      "https://i.dummyjson.com/data/products/19/3.png",
      "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    ],
  },
  {
    id: 20,
    title: "Freckle Treatment Cream- 15gm",
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    price: 70,
    discountPercentage: 16.99,
    rating: 4.06,
    stock: 140,
    brand: "Fair & Clear",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/20/1.jpg",
      "https://i.dummyjson.com/data/products/20/2.jpg",
      "https://i.dummyjson.com/data/products/20/3.jpg",
      "https://i.dummyjson.com/data/products/20/4.jpg",
      "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    ],
  },
  {
    id: 21,
    title: "- Daal Masoor 500 grams",
    description: "Fine quality Branded Product Keep in a cool and dry place",
    price: 20,
    discountPercentage: 4.81,
    rating: 4.44,
    stock: 133,
    brand: "Saaf & Khaas",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.png",
    images: [
      "https://i.dummyjson.com/data/products/21/1.png",
      "https://i.dummyjson.com/data/products/21/2.jpg",
      "https://i.dummyjson.com/data/products/21/3.jpg",
    ],
  },
  {
    id: 22,
    title: "Elbow Macaroni - 400 gm",
    description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
    price: 14,
    discountPercentage: 15.58,
    rating: 4.57,
    stock: 146,
    brand: "Bake Parlor Big",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/22/1.jpg",
      "https://i.dummyjson.com/data/products/22/2.jpg",
      "https://i.dummyjson.com/data/products/22/3.jpg",
    ],
  },
  {
    id: 23,
    title: "Orange Essence Food Flavou",
    description:
      "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
    price: 14,
    discountPercentage: 8.04,
    rating: 4.85,
    stock: 26,
    brand: "Baking Food Items",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/23/1.jpg",
      "https://i.dummyjson.com/data/products/23/2.jpg",
      "https://i.dummyjson.com/data/products/23/3.jpg",
      "https://i.dummyjson.com/data/products/23/4.jpg",
      "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    ],
  },
  {
    id: 24,
    title: "cereals muesli fruit nuts",
    description:
      "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
    price: 46,
    discountPercentage: 16.8,
    rating: 4.94,
    stock: 113,
    brand: "fauji",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/24/1.jpg",
      "https://i.dummyjson.com/data/products/24/2.jpg",
      "https://i.dummyjson.com/data/products/24/3.jpg",
      "https://i.dummyjson.com/data/products/24/4.jpg",
      "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    ],
  },
  {
    id: 25,
    title: "Gulab Powder 50 Gram",
    description: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
    price: 70,
    discountPercentage: 13.58,
    rating: 4.87,
    stock: 47,
    brand: "Dry Rose",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/25/1.png",
      "https://i.dummyjson.com/data/products/25/2.jpg",
      "https://i.dummyjson.com/data/products/25/3.png",
      "https://i.dummyjson.com/data/products/25/4.jpg",
      "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    ],
  },
  {
    id: 26,
    title: "Plant Hanger For Home",
    description:
      "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
    price: 41,
    discountPercentage: 17.86,
    rating: 4.08,
    stock: 131,
    brand: "Boho Decor",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/26/1.jpg",
      "https://i.dummyjson.com/data/products/26/2.jpg",
      "https://i.dummyjson.com/data/products/26/3.jpg",
      "https://i.dummyjson.com/data/products/26/4.jpg",
      "https://i.dummyjson.com/data/products/26/5.jpg",
      "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    ],
  },
  {
    id: 27,
    title: "Flying Wooden Bird",
    description:
      "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    price: 51,
    discountPercentage: 15.58,
    rating: 4.41,
    stock: 17,
    brand: "Flying Wooden",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/27/1.jpg",
      "https://i.dummyjson.com/data/products/27/2.jpg",
      "https://i.dummyjson.com/data/products/27/3.jpg",
      "https://i.dummyjson.com/data/products/27/4.jpg",
      "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    ],
  },
  {
    id: 28,
    title: "3D Embellishment Art Lamp",
    description:
      "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
    price: 20,
    discountPercentage: 16.49,
    rating: 4.82,
    stock: 54,
    brand: "LED Lights",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/28/1.jpg",
      "https://i.dummyjson.com/data/products/28/2.jpg",
      "https://i.dummyjson.com/data/products/28/3.png",
      "https://i.dummyjson.com/data/products/28/4.jpg",
      "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    ],
  },
  {
    id: 29,
    title: "Handcraft Chinese style",
    description:
      "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    price: 60,
    discountPercentage: 15.34,
    rating: 4.44,
    stock: 7,
    brand: "luxury palace",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/29/1.jpg",
      "https://i.dummyjson.com/data/products/29/2.jpg",
      "https://i.dummyjson.com/data/products/29/3.webp",
      "https://i.dummyjson.com/data/products/29/4.webp",
      "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    ],
  },
  {
    id: 30,
    title: "Key Holder",
    description:
      "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
    price: 30,
    discountPercentage: 2.92,
    rating: 4.92,
    stock: 54,
    brand: "Golden",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/30/1.jpg",
      "https://i.dummyjson.com/data/products/30/2.jpg",
      "https://i.dummyjson.com/data/products/30/3.jpg",
      "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    ],
  },
];
export const brand = [
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
];
export const posts = [
  {
    id: 1,
    title: "His mother had always taught him",
    body: "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
    userId: 9,
    tags: ["history", "american", "crime"],
    reactions: 2,
  },
  {
    id: 2,
    title: "He was an expert but not in a discipline",
    body: "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
    userId: 13,
    tags: ["french", "fiction", "english"],
    reactions: 2,
  },
  {
    id: 3,
    title: "Dave watched as the forest burned up on the hill.",
    body: "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to round up the last of the pets. Dave went through his mental list of the most important papers and documents that they couldn't leave behind. He scolded himself for not having prepared these better in advance and hoped that he had remembered everything that was needed. He continued to wait for Marta to appear with the pets, but she still was nowhere to be seen.",
    userId: 32,
    tags: ["magical", "history", "french"],
    reactions: 5,
  },
  {
    id: 4,
    title: "All he wanted was a candy bar.",
    body: "All he wanted was a candy bar. It didn't seem like a difficult request to comprehend, but the clerk remained frozen and didn't seem to want to honor the request. It might have had something to do with the gun pointed at his face.",
    userId: 12,
    tags: ["mystery", "english", "american"],
    reactions: 1,
  },
  {
    id: 5,
    title: "Hopes and dreams were dashed that day.",
    body: "Hopes and dreams were dashed that day. It should have been expected, but it still came as a shock. The warning signs had been ignored in favor of the possibility, however remote, that it could actually happen. That possibility had grown from hope to an undeniable belief it must be destiny. That was until it wasn't and the hopes and dreams came crashing down.",
    userId: 41,
    tags: ["crime", "mystery", "love"],
    reactions: 2,
  },
  {
    id: 6,
    title: "Dave wasn't exactly sure how he had ended up",
    body: "Dave wasn't exactly sure how he had ended up in this predicament. He ran through all the events that had lead to this current situation and it still didn't make sense. He wanted to spend some time to try and make sense of it all, but he had higher priorities at the moment. The first was how to get out of his current situation of being naked in a tree with snow falling all around and no way for him to get down.",
    userId: 47,
    tags: ["english", "classic", "american"],
    reactions: 3,
  },
  {
    id: 7,
    title: "This is important to remember.",
    body: "This is important to remember. Love isn't like pie. You don't need to divide it among all your friends and loved ones. No matter how much love you give, you can always give more. It doesn't run out, so don't try to hold back giving it as if it may one day run out. Give it freely and as much as you want.",
    userId: 12,
    tags: ["magical", "crime"],
    reactions: 0,
  },
  {
    id: 8,
    title: "One can cook on and with an open fire.",
    body: "One can cook on and with an open fire. These are some of the ways to cook with fire outside. Cooking meat using a spit is a great way to evenly cook meat. In order to keep meat from burning, it's best to slowly rotate it.",
    userId: 31,
    tags: ["american", "english"],
    reactions: 9,
  },
  {
    id: 9,
    title: "There are different types of secrets.",
    body: "There are different types of secrets. She had held onto plenty of them during her life, but this one was different. She found herself holding onto the worst type. It was the type of secret that could gnaw away at your insides if you didn't tell someone about it, but it could end up getting you killed if you did.",
    userId: 42,
    tags: ["american", "history", "magical"],
    reactions: 2,
  },
  {
    id: 10,
    title: "They rushed out the door.",
    body: "They rushed out the door, grabbing anything and everything they could think of they might need. There was no time to double-check to make sure they weren't leaving something important behind. Everything was thrown into the car and they sped off. Thirty minutes later they were safe and that was when it dawned on them that they had forgotten the most important thing of all.",
    userId: 1,
    tags: ["fiction", "magical", "history"],
    reactions: 4,
  },
  {
    id: 11,
    title: "It wasn't quite yet time to panic.",
    body: "It wasn't quite yet time to panic. There was still time to salvage the situation. At least that is what she was telling himself. The reality was that it was time to panic and there wasn't time to salvage the situation, but he continued to delude himself into believing there was.",
    userId: 25,
    tags: ["mystery", "american", "history"],
    reactions: 5,
  },
  {
    id: 12,
    title: "She was aware that things could go wrong.",
    body: "She was aware that things could go wrong. In fact, she had trained her entire life in anticipation that things would go wrong one day. She had quiet confidence as she started to see that this was the day that all her training would be worthwhile and useful. At this point, she had no idea just how wrong everything would go that day.",
    userId: 26,
    tags: ["love", "english"],
    reactions: 7,
  },
  {
    id: 13,
    title: "She wanted rainbow hair.",
    body: "She wanted rainbow hair. That's what she told the hairdresser. It should be deep rainbow colors, too. She wasn't interested in pastel rainbow hair. She wanted it deep and vibrant so there was no doubt that she had done this on purpose.",
    userId: 44,
    tags: ["mystery", "classic", "french"],
    reactions: 0,
  },
  {
    id: 14,
    title: "The paper was blank.",
    body: "The paper was blank. It shouldn't have been. There should have been writing on the paper, at least a paragraph if not more. The fact that the writing wasn't there was frustrating. Actually, it was even more than frustrating. It was downright distressing.",
    userId: 1,
    tags: ["mystery", "english", "love"],
    reactions: 0,
  },
  {
    id: 15,
    title: "The trees, therefore, must be such old",
    body: "The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious. At that, they probably didn't have too much time after they detected us orbiting and intending to land. And if that were true, there could be only one place where their civilization was hidden.",
    userId: 15,
    tags: ["fiction", "history", "crime"],
    reactions: 1,
  },
  {
    id: 16,
    title: "There was only one way to do things in the Statton house.",
    body: "There was only one way to do things in the Statton house. That one way was to do exactly what the father, Charlie, demanded. He made the decisions and everyone else followed without question. That was until today.",
    userId: 31,
    tags: ["magical", "french", "american"],
    reactions: 5,
  },
  {
    id: 17,
    title: "She was in a hurry.",
    body: "She was in a hurry. Not the standard hurry when you're in a rush to get someplace, but a frantic hurry. The type of hurry where a few seconds could mean life or death. She raced down the road ignoring speed limits and weaving between cars. She was only a few minutes away when traffic came to a dead standstill on the road ahead.",
    userId: 5,
    tags: ["french", "magical", "english"],
    reactions: 0,
  },
  {
    id: 18,
    title: "She had a terrible habit o comparing her life to others",
    body: "She had a terrible habit o comparing her life to others. She realized that their life experiences were completely different than her own and that she saw only what they wanted her to see, but that didn't matter. She still compared herself and yearned for what she thought they had and she didn't.",
    userId: 28,
    tags: ["history", "french", "love"],
    reactions: 3,
  },
  {
    id: 19,
    title: "The rain and wind abruptly stopped.",
    body: "The rain and wind abruptly stopped, but the sky still had the gray swirls of storms in the distance. Dave knew this feeling all too well. The calm before the storm. He only had a limited amount of time before all Hell broke loose, but he stopped to admire the calmness. Maybe it would be different this time, he thought, with the knowledge deep within that it wouldn't.",
    userId: 46,
    tags: ["fiction", "crime", "magical"],
    reactions: 8,
  },
  {
    id: 20,
    title: "He couldn't remember exactly where he had read it",
    body: "He couldn't remember exactly where he had read it, but he was sure that he had. The fact that she didn't believe him was quite frustrating as he began to search the Internet to find the article. It wasn't as if it was something that seemed impossible. Yet she insisted on always seeing the source whenever he stated a fact.",
    userId: 38,
    tags: ["french", "classic"],
    reactions: 9,
  },
  {
    id: 21,
    title: "He wandered down the stairs and into the basement",
    body: "He wandered down the stairs and into the basement. The damp, musty smell of unuse hung in the air. A single, small window let in a glimmer of light, but this simply made the shadows in the basement deeper. He inhaled deeply and looked around at a mess that had been accumulating for over 25 years. He was positive that this was the place he wanted to live.",
    userId: 37,
    tags: ["french", "american"],
    reactions: 8,
  },
  {
    id: 22,
    title: "She has seen this scene before.",
    body: "She has seen this scene before. It had come to her in dreams many times before. She had to pinch herself to make sure it wasn't a dream again. As her fingers squeezed against her arm, she felt the pain. It was this pain that immediately woke her up.",
    userId: 30,
    tags: ["classic", "love", "history"],
    reactions: 6,
  },
  {
    id: 23,
    title:
      "It's an unfortunate reality that we don't teach people how to make money",
    body: "It's an unfortunate reality that we don't teach people how to make money (beyond getting a 9 to 5 job) as part of our education system. The truth is there are a lot of different, legitimate ways to make money. That doesn't mean they are easy and that you won't have to work hard to succeed, but it does mean that if you're willing to open your mind a bit you don't have to be stuck in an office from 9 to 5 for the next fifty years o your life.",
    userId: 2,
    tags: ["crime", "english"],
    reactions: 4,
  },
  {
    id: 24,
    title: "The robot clicked disapprovingly.",
    body: 'The robot clicked disapprovingly, gurgled briefly inside its cubical interior and extruded a pony glass of brownish liquid. "Sir, you will undoubtedly end up in a drunkard\'s grave, dead of hepatic cirrhosis," it informed me virtuously as it returned my ID card. I glared as I pushed the glass across the table.',
    userId: 34,
    tags: ["crime", "american", "love"],
    reactions: 2,
  },
  {
    id: 25,
    title: "It went through such rapid contortions",
    body: "It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust.",
    userId: 27,
    tags: ["fiction", "history", "french"],
    reactions: 3,
  },
  {
    id: 26,
    title: "She patiently waited for his number to be called.",
    body: "She patiently waited for his number to be called. She had no desire to be there, but her mom had insisted that she go. She's resisted at first, but over time she realized it was simply easier to appease her and go. Mom tended to be that way. She would keep insisting until you wore down and did what she wanted. So, here she sat, patiently waiting for her number to be called.",
    userId: 27,
    tags: ["french", "mystery", "crime"],
    reactions: 7,
  },
  {
    id: 27,
    title: "Ten more steps.",
    body: "If he could take ten more steps it would be over, but his legs wouldn't move. He tried to will them to work, but they wouldn't listen to his brain. Ten more steps and it would be over but it didn't appear he would be able to do it.",
    userId: 17,
    tags: ["mystery", "classic", "love"],
    reactions: 4,
  },
  {
    id: 28,
    title: "He had three simple rules by which he lived.",
    body: "He had three simple rules by which he lived. The first was to never eat blue food. There was nothing in nature that was edible that was blue. People often asked about blueberries, but everyone knows those are actually purple. He understood it was one of the stranger rules to live by, but it had served him well thus far in the 50+ years of his life.",
    userId: 22,
    tags: ["crime", "love"],
    reactions: 2,
  },
  {
    id: 29,
    title: "The chair sat in the corner where it had been",
    body: "The chair sat in the corner where it had been for over 25 years. The only difference was there was someone actually sitting in it. How long had it been since someone had done that? Ten years or more he imagined. Yet there was no denying the presence in the chair now.",
    userId: 38,
    tags: ["mystery", "american"],
    reactions: 6,
  },
  {
    id: 30,
    title: "Things aren't going well at all",
    body: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
    userId: 2,
    tags: ["american", "love", "fiction"],
    reactions: 0,
  },
];
export const carousel = [
  "https://www.youtube.com/shorts/FZsOm-qARPM",
  "https://www.youtube.com/shorts/3k01apyZFlI",
  "https://www.youtube.com/shorts/aWVzZgbOVhw",
  "https://www.youtube.com/shorts/46NfO75pf3w",
];

export const adminCard = [
  {
    title: "cost",
    value: 1044002,
  },
  {
    title: "request",
    value: 128,
  },
  {
    title: "order",
    value: 228,
  },
  {
    title: "complete",
    value: 208,
  },
  {
    title: "cancel",
    value: 58,
  },
];

export const areaChart = [
  {
    month: 1,
    order: 7,
    request: 2,
  },
  {
    month: 2,
    order: 12,
    request: 32,
  },
  {
    month: 3,
    order: 7,
    request: 10,
  },
  {
    month: 4,
    order: 4,
    request: 2,
  },
  {
    month: 5,
    order: 7,
    request: 2,
  },
];
export const heatMap = [
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 43,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 43,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 43,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 43,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 88,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 21,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 43,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
  {
    name: "6 am",
    data: [
      {
        x: "Mon",
        y: 43,
      },
      {
        x: "Tue",
        y: 10,
      },
      {
        x: "Wed",
        y: 43,
      },
      {
        x: "Thu",
        y: 43,
      },
      {
        x: "Fri",
        y: 43,
      },
      {
        x: "Sat",
        y: 43,
      },
      {
        x: "Sun",
        y: 43,
      },
    ],
  },
];
export const orderTable = [
  {
    id: 1,
    name: "iphone 14 Max Pro",
    date: "20-10-2023",
    user: "John Doe",
    status: "paid",
    items: 1,
    total: 4299,
  },
  {
    id: 2,
    name: "Samsung S23 Ultra",
    date: "12-10-2023",
    user: "John Doe",
    status: "processing",
    items: 3,
    total: 4299,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "shipping",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "cancelled",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "pending",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "cancelled",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "completed",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "refunded",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "refundProcessing",
    items: 1,
    total: 6789,
  },
  {
    id: 3,
    name: "Mackbook Pro",
    date: "20-9-2023",
    user: "Brad",
    status: "refundCancelled",
    items: 1,
    total: 6789,
  },
];
export const requestTable = [
  {
    id: 2050,
    product: "iphone 14 Max Pro",
    link: "www.amazon.com/iphone-14-max-pro",
    date: "20-10-2023",
    customer: "John Doe",
    status: "paid",
  },
  {
    id: 2,
    product: "iphone 14 Max Pro",
    link: "www.amazon.com/iphone-14-max-pro",
    date: "20-10-2023",
    customer: "John Doe",
    status: "abandoned",
  },
  {
    id: 3,
    product: "iphone 14 Max Pro",
    link: "www.amazon.com/iphone-14-max-pro",
    date: "20-10-2023",
    customer: "John Doe",
    status: "estimate",
  },
  {
    id: 3,
    product: "iphone 14 Max Pro",
    link: "www.amazon.com/iphone-14-max-pro",
    date: "20-10-2023",
    customer: "John Doe",
    status: "closed",
  },
  {
    id: 3,
    product: "iphone 14 Max Pro",
    link: "www.amazon.com/iphone-14-max-pro",
    date: "20-10-2023",
    customer: "John Doe",
    status: "pending",
  },
  {
    id: 3,
    product: "iphone 14 Max Pro",
    link: "www.amazon.com/iphone-14-max-pro",
    date: "20-10-2023",
    customer: "John Doe",
    status: "closed",
  },
];
export const chatCardData = [
  {
    id: 1,
    status: "open",
    type: "payment",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 2,
    status: "close",
    type: "payment",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 3,
    status: "pending",
    type: "payment",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 4,
    status: "open",
    type: "refund",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 5,
    status: "close",
    type: "account",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 6,
    status: "open",
    type: "account",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 7,
    status: "close",
    type: "order",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
  {
    id: 8,
    status: "open",
    type: "account",
    message:
      "t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,",
  },
];

export const customer = [
  {
    id: 1,
    name: "David Miller",
    phone: "+1643634234",
    location: "West St, California, USA",
    orders: 22,
    spent: 2009,
  },
  {
    id: 2,
    name: "Sofia Willam",
    phone: "+1643634234",
    location: "West St, California, USA",
    orders: 2,
    spent: 209,
  },
  {
    id: 3,
    name: "Jhon Doe",
    phone: "+1643634234",
    location: "West St, California, USA",
    orders: 22,
    spent: 2009,
  },
  {
    id: 4,
    name: "Sara Luke",
    phone: "+1643634234",
    location: "West St, California, USA",
    orders: 22,
    spent: 2009,
  },
  {
    id: 5,
    name: "Diana Dacancy",
    phone: "+1643634234",
    location: "West St, California, USA",
    orders: 22,
    spent: 2009,
  },
];

export const customerDetails = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    status: "pending",
    image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 533,
    status: "paid",
    image: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 422,
    status: "cancelled",
    image: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    status: "shipping",
    image: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    image: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    status: "completed",
  },
];
export const discountData = [
  {
    code: "#1234",
    type: "Fixed cart discount",
    amount: 10,
    description: "10৳ off",
    usage: "0 / ∞",
    expiry: "Dec 7, 2019",
  },
  {
    code: "#2345",
    type: "Fixed cart discount",
    amount: 10,
    description: "10৳ off",
    usage: "0 / ∞",
    expiry: "Dec 7, 2019",
  },
  {
    code: "#4564",
    type: "Fixed cart discount",
    amount: 10,
    description: "10৳ off",
    usage: "0 / ∞",
    expiry: "Dec 7, 2019",
  },
  {
    code: "#2473",
    type: "Fixed cart discount",
    amount: 10,
    description: "10৳ off",
    usage: "0 / ∞",
    expiry: "Dec 7, 2019",
  },
  {
    code: "#9097",
    type: "Fixed cart discount",
    amount: 10,
    description: "10৳ off",
    usage: "0 / ∞",
    expiry: "Dec 7, 2019",
  },
  {
    code: "#43545",
    type: "Fixed cart discount",
    amount: 10,
    description: "10৳ off",
    usage: "0 / ∞",
    expiry: "Dec 7, 2019",
  },
];

export const categoryData = [
  {
    id: 1,
    name: "Electronics",
    slug: "electric",
    post: 10,
  },
  {
    id: 2,
    name: "Electronics",
    slug: "electric",
    post: 10,
  },
  {
    id: 3,
    name: "Electronics",
    slug: "electric",
    post: 10,
  },
  {
    id: 4,
    name: "Electronics",
    slug: "electric",
    post: 10,
  },
  {
    id: 5,
    name: "Electronics",
    slug: "electric",
    post: 10,
  },
];

export const paymentList = [
  {
    id: 1231,
    customer: "Guy Hawkins",
    date: "Today at 6:55am",
    amount: 12341,
    status: "pending",
  },
  {
    id: 1232,
    customer: "Guy Hawkins",
    date: "Today at 6:55am",
    amount: 12341,
    status: "cancelled",
  },
  {
    id: 1233,
    customer: "Guy Hawkins",
    date: "Today at 6:55am",
    amount: 12341,
    status: "paid",
  },
  {
    id: 1234,
    customer: "Guy Hawkins",
    date: "Today at 6:55am",
    amount: 12341,
    status: "completed",
  },
  {
    id: 1235,
    customer: "Guy Hawkins",
    date: "Today at 6:55am",
    amount: 12341,
    status: "pending",
  },
];

export const chatData = [
  {
    type: "customer",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "user",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "customer",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "customer",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "user",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "customer",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "user",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "customer",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "customer",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
  {
    type: "user",
    date: "4 aug",
    message: "lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor",
  },
];

export const suppoortArticles = [
  "How do I pay for items?",
  "	What is Backpack? How do I order items?",
  "How do I pay for items?",
  "	What is Backpack? How do I order items?",
  "	What is Backpack? How do I order items?",
  "	What is Backpack? How do I order items?",
];
